[project]
name = "advance-lang-chain-techniques"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.18",
    "langchain-openai>=0.3.5",
]
